#!/bin/sh

function_start_mysql()
{
printf "Starting MySQL...\n"
/bin/sh /usr/local/webserver/mysql/bin/mysqld_safe --defaults-file=/usr/local/webserver/mysql/my.cnf &
}

function_stop_mysql()
{
printf "Stopping MySQL...\n"
/usr/local/webserver/mysql/bin/mysqladmin -u mysql -pmysql shutdown
}

function_restart_mysql()
{
printf "Restarting MySQL...\n"
function_stop_mysql
sleep 5
function_start_mysql
}

function_kill_mysql()
{
kill -9 $(ps -ef | grep 'bin/mysqld_safe' | grep 3306 | awk '{printf $2}')
kill -9 $(ps -ef | grep 'libexec/mysqld' | grep 3306 | awk '{printf $2}')
}

if [ "$1" = "start" ]; then
function_start_mysql
elif [ "$1" = "stop" ]; then
function_stop_mysql
elif [ "$1" = "restart" ]; then
function_restart_mysql
elif [ "$1" = "kill" ]; then
function_kill_mysql
else
printf "Usage: /usr/local/webserver/mysql {start|stop|restart|kill}\n"
fi
